[package]
name = "rv32i-emulator"
version = "0.1.0"
authors = ["Ayush Kamat <akamat@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
